version: "3.8"
services:
  apache:
    build: 
      context: ./apache
      args:
        APACHE_VERSION: ${APACHE_VERSION}
        APACHE_CRON_MINUTO: ${APACHE_CRON_MINUTO}
        APACHE_CRON_HORA: ${APACHE_CRON_HORA}
        APACHE_CRON_DIA_MES: ${APACHE_CRON_DIA_MES}
        APACHE_CRON_MES: ${APACHE_CRON_MES}
        APACHE_CRON_DIA_SEMANA: ${APACHE_CRON_DIA_SEMANA}
        TZDATA: ${TZDATA}
    image: "daw-apache-ssl:2021.11"
    container_name: daw-apache-ssl
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    environment:
      APACHE_GLOBAL_ServerName: ${APACHE_GLOBAL_ServerName}
      APACHE_VH_ServerName: ${APACHE_VH_ServerName}
      APACHE_VH_ServerAlias: ${APACHE_VH_ServerAlias}
      LETS_ENCRYPT_EMAIL: ${LETS_ENCRYPT_EMAIL} 
      LETS_ENCRYPT_DOMINIOS: ${LETS_ENCRYPT_DOMINIOS}
      LETS_ENCRYPT_DIR: ${LETS_ENCRYPT_DIR}
    volumes:
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
      - ${PROYECTO_RUTA}:/var/www/html
    networks:
      daw-red-www-ssl:

networks: 
  daw-red-www-ssl:
    name: daw-red-www-ssl
volumes:
  varletsencrypt:
    name: daw-varletsencrypt
  etcletsencrypt:
    name: daw-etcletsencrypt
